services:
    postgres:
        environment:
        # Mount data hereonment:
            PGDATA: /var/lib/postgresql/data/gdata
            POSTGRES_PASSWORD: superuser_password
        image: postgres:13
        ports:
        - 127.0.0.1:5432:5432
        restart: always
        volumes:
        # Mount data here. should be parallel to the environment variable above
        - ./localdata/postgres/:/var/lib/postgresql/data
        # Mount initialization scripts here.
        # The format is https://github.com/docker-library/postgres/issues/313
        - ./init/postgres/:/docker-entrypoint-initdb.d
    elasticsearch:
        environment:
            ES_JAVA_OPTS: -Xms1g -Xmx1g
            discovery.type: single-node
        image: 925941946834.dkr.ecr.us-east-2.amazonaws.com/chinese-elastic
        ports:
        - 127.0.0.1:9200:9200
        - 127.0.0.1:9300:9300
        restart: always
        volumes:
        - ./localdata/elasticsearch/:/elasticsearch/data
    redis:
        image: redis:4-alpine
        command: redis-server --requirepass localpassword
        ports:
            - 127.0.0.1:6379:6379
        restart: always
version: '3.3'
